### ISSUE TITLE
Automatically selecting the proper PHANTASYSTARONLINE2 directory

### ISSUE THREAD

**Issue by ImportTaste** [masayoshi4649/PSO2NGSLogViewer#23]
On the Global region, the folder used can be one of these three:

Microsoft: `PHANTASYSTARONLINE2_NA`
Epic Games: `PHANTASYSTARONLINE2_NA_EPICGAMES`
Steam: `PHANTASYSTARONLINE2_NA_STEAM`

My suggestion is this... Get rid of `appSetting["client"]`, and use this code instead:

```javascript
const glob = require("glob");
const fs = require("fs");
```
```javascript
const PSO2_DIR = glob.sync(app.getPath("documents") + "\\SEGA\\PHANTASYSTARONLINE2*")
  .map(name => ({name, ctime: fs.statSync(name).ctime}))
  .sort((a, b) => b.ctime - a.ctime)[0].name
  .replaceAll('/','\\');

const LOG_CLASSIC = PSO2_DIR.concat("\\log\\");
const LOG_NGS = PSO2_DIR.concat("\\log_ngs\\");
```
`PSO2_DIR` will return the PHANTASYSTARONLINE2 folder that contains the most recently modified files.

I've included a `PSO2_CLASSIC` variable; because, it seems the original game still uses its own log files. It would be good if those were eventually supported as well.

**Comment by masayoshi4649** [comment]
Marged that code.
Thanks.

PSO2_CLASSIC Support on 2021.09.03 too.
